# Generated by Django 4.2 on 2023-04-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bowlaniwi', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=500, verbose_name='Topshiriq nomi')),
                ('is_complete', models.BooleanField(default=False, verbose_name='Yakunlandi')),
                ('info', models.TextField()),
                ('yakunlaniwi', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Topshiriq',
                'verbose_name_plural': 'Topshiriq',
            },
        ),
    ]
