# Generated by Django 4.2 on 2023-04-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_todo_bowlaniwi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='yakunlaniwi',
            field=models.DateField(auto_now=True),
        ),
    ]
